export const other = [
  { text: "Welcome", link: "/杂项/" },
  {
    text: "浏览器-协议",
    collapsed: false,
    items: [
      { text: "http", link: "/杂项/浏览器-协议/http" },
      {
        text: "对称加密和非对称加密",
        link: "/杂项/浏览器-协议/对称加密和非对称加密",
      },
      { text: "tcp", link: "/杂项/浏览器-协议/tcp" },
      { text: "websocket", link: "/杂项/浏览器-协议/websocket" },
      { text: "dns", link: "/杂项/浏览器-协议/dns" },
      { text: "服务端推送", link: "/杂项/浏览器-协议/服务端推送" },
      { text: "浏览器进程", link: "/杂项/浏览器-协议/浏览器进程" },
      { text: "浏览器渲染网页", link: "/杂项/浏览器-协议/浏览器渲染网页" },
      { text: "DOM树", link: "/杂项/浏览器-协议/DOM树" },
      { text: "浏览器存储", link: "/杂项/浏览器-协议/浏览器存储" },
      { text: "浏览器窗口间通信", link: "/杂项/浏览器-协议/浏览器窗口间通信" },
      { text: "浏览器内核", link: "/杂项/浏览器-协议/浏览器内核" },
      { text: "JS引擎", link: "/杂项/浏览器-协议/JS引擎" },
    ],
  },
  {
    text: "操作系统",
    collapsed: false,
    items: [
      { text: "进程和线程", link: "/杂项/操作系统/进程和线程" },
      { text: "死锁", link: "/杂项/操作系统/死锁" },
    ],
  },
  {
    text: "安全",
    collapsed: false,
    items: [
      { text: "web安全", link: "/杂项/安全/web安全" },
      { text: "同源策略", link: "/杂项/安全/同源策略" },
      { text: "内容安全策略", link: "/杂项/安全/CSP" },
      { text: "XSS和CSRF", link: "/杂项/安全/XSS和CSRF" },
    ],
  },
  {
    text: "手写代码",
    collapsed: false,
    items: [
      { text: "Promise", link: "/杂项/手写代码/Promise" },
      { text: "防抖节流", link: "/杂项/手写代码/防抖节流" },
      { text: "call-apply-bind", link: "/杂项/手写代码/call-apply-bind" },
      { text: "深拷贝和浅拷贝", link: "/杂项/手写代码/深拷贝和浅拷贝" },
      { text: "instanceOf", link: "/杂项/手写代码/instanceOf" },
      { text: "数组扁平化", link: "/杂项/手写代码/数组扁平化" },
      { text: "柯里化", link: "/杂项/手写代码/柯里化" },
      { text: "数组reduce", link: "/杂项/手写代码/数组reduce" },
      { text: "代码片段", link: "/杂项/手写代码/代码片段" },
      { text: "React写一个倒计时", link: "/杂项/手写代码/React写一个倒计时" },
    ],
  },
  {
    text: "代码格式",
    collapsed: false,
    items: [
      { text: "Eslint", link: "/杂项/代码格式/Eslint" },
      { text: "prettier", link: "/杂项/代码格式/prettier" },
      { text: "stylelint", link: "/杂项/代码格式/stylelint" },
      { text: "husky", link: "/杂项/代码格式/husky" },
      { text: "commitlint", link: "/杂项/代码格式/commitlint" },
    ],
  },
  {
    text: "常用操作",
    collapsed: false,
    items: [{ text: "遍历", link: "/杂项/常用操作/遍历" }],
  },
];
